"""Regenerate ``tests/TESTS.md`` from the actually-collected suite.

Collects the suite with ``pytest --collect-only -q``, groups the collected
node ids by test file, and emits one line per file: path, test count, and the
first line of the file's module docstring. Output is deterministic — files
sorted by path, counts from the live collection, no timestamps — so a CI drift
step can assert ``git diff --exit-code tests/TESTS.md`` stays clean.

The point of this generator is that TESTS.md can never again drift into
fiction: it lists exactly what pytest collects, nothing aspirational. Intent
that is genuinely planned but not yet built lives in a short, clearly-labelled
"Planned, not implemented" section (below), capped so aspiration and fact can
never be confused.

Run: ``uv run python scripts/gen_tests_md.py``
"""
from __future__ import annotations

import ast
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TESTS_DIR = ROOT / "tests"
OUTPUT = TESTS_DIR / "TESTS.md"

_NODE_RE = re.compile(r"^(?P<path>tests/[^\s:]+\.py)::")

#: Intent recorded but not yet built — capped at five lines so it can never
#: masquerade as coverage. Each line is a still-unimplemented test surface;
#: delete a line the moment the corresponding test file lands (the collected
#: section above will then carry it as fact).
PLANNED: list[str] = [
    "`own-vs-oracle leg` — three-way ffn/empyrical oracle comparison (this "
    "phase built the published leg only).",
    "`direct >= regular` — paired direct-growth vs regular-growth ordering "
    "over matched windows.",
    "`determinism` — the pipeline run twice on frozen fixtures yields "
    "identical metric outputs.",
    "`no-live-fetch guard` — analysis/compute paths never import or call the "
    "mftool client.",
    "`category coverage` — every SEBI category (FoF, multi-asset, liquid, "
    "debt) computes within a plausible band.",
]


def _module_docstring_first_line(path: Path) -> str:
    """First non-empty line of ``path``'s module docstring, or a plain marker."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError):
        return "(unparseable)"
    doc = ast.get_docstring(tree)
    if not doc:
        return "(no module docstring)"
    for line in doc.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return "(no module docstring)"


def _collect_counts() -> dict[str, int]:
    """Test count per file, from a live ``pytest --collect-only -q`` run."""
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "tests"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit(
            f"pytest collection failed (exit {result.returncode}); "
            "TESTS.md not regenerated"
        )

    counts: dict[str, int] = {}
    for line in result.stdout.splitlines():
        match = _NODE_RE.match(line.strip())
        if match:
            counts[match.group("path")] = counts.get(match.group("path"), 0) + 1
    return counts


def render(counts: dict[str, int]) -> str:
    """The full deterministic TESTS.md body."""
    total = sum(counts.values())
    lines: list[str] = [
        "# tests/ — the gate",
        "",
        "Generated by `scripts/gen_tests_md.py` — do not edit by hand. "
        "Regenerate after adding or removing tests; CI fails on drift.",
        "",
        f"{len(counts)} test files, {total} collected tests. "
        "All fixtures load from `fixtures/` only; no test touches the network.",
        "",
        "## Collected",
        "",
    ]
    for path in sorted(counts):
        count = counts[path]
        noun = "test" if count == 1 else "tests"
        description = _module_docstring_first_line(ROOT / path)
        lines.append(f"- `{path}` — {count} {noun} — {description}")

    lines += ["", "## Planned, not implemented", ""]
    for entry in PLANNED[:5]:
        lines.append(f"- {entry}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    body = render(_collect_counts())
    OUTPUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
