"""Regenerate the ``## Capability inventory`` section of ``ARCHITECTURE.md``.

Walks ``src/foliolens/``, emits one line per module — path and the first
sentence of that module's docstring — grouped by package. Output is
deterministic (modules sorted by path, first sentence taken mechanically from
the docstring, no timestamps) and is written *between markers* so a CI drift
step can assert ``git diff --exit-code ARCHITECTURE.md`` stays clean, exactly
like ``scripts/gen_tests_md.py`` does for ``tests/TESTS.md``.

This is the anti-commentary mechanism applied to the module tree: a new module
cannot exist without announcing itself (a docstring-less module lands as a
loud ``(no module docstring)`` line the drift check refuses to ignore), and the
inventory can never rot away from the code it describes.

Where a docstring's first sentence reads unclearly, fix the *docstring* — this
generator paraphrases nothing.

Run: ``uv run python scripts/gen_inventory.py``
"""
from __future__ import annotations

import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "foliolens"
ARCHITECTURE = ROOT / "ARCHITECTURE.md"

BEGIN = "<!-- BEGIN capability-inventory (generated by scripts/gen_inventory.py; do not edit) -->"
END = "<!-- END capability-inventory -->"

#: Abbreviations whose trailing dot must not be mistaken for a sentence end.
_ABBR = ("e.g.", "i.e.", "etc.", "vs.", "cf.", "al.", "no.")
_PERIOD = re.compile(r"\.(?=\s|$)")


def _first_sentence(doc: str) -> str:
    """The first sentence of ``doc``, whitespace-reflowed onto one line.

    A sentence ends at the first period followed by whitespace or end-of-text,
    skipping the handful of abbreviations whose dot is not a full stop. A
    docstring with no such period is returned whole (with a trailing period
    added if missing) — the corpus's one-fragment docstrings read fine that way.
    """
    text = re.sub(r"\s+", " ", doc.strip())
    for match in _PERIOD.finditer(text):
        candidate = text[: match.end()]
        if any(candidate.lower().endswith(abbr) for abbr in _ABBR):
            continue
        return candidate
    return text if text.endswith(".") else text + "."


def _module_first_sentence(path: Path) -> str:
    """First sentence of ``path``'s module docstring, or a loud marker."""
    try:
        doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8")))
    except (OSError, SyntaxError):
        return "(unparseable)"
    if not doc:
        return "(no module docstring)"
    return _first_sentence(doc)


def collect_modules() -> list[tuple[str, str, str]]:
    """``(package, module_filename, first_sentence)`` for every module, sorted.

    ``package`` is the dotted import path of the module's parent package
    (``foliolens.analytics`` etc.); ``module_filename`` is the bare file name.
    Sorted by ``(package, filename)`` so each package is one contiguous block
    and the output is stable across machines and runs.
    """
    rows: list[tuple[str, str, str]] = []
    for path in SRC.rglob("*.py"):
        rel = path.relative_to(SRC)
        package = ".".join(("foliolens", *rel.parent.parts))
        rows.append((package, path.name, _module_first_sentence(path)))
    return sorted(rows, key=lambda row: (row[0], row[1]))


def render_body(rows: list[tuple[str, str, str]]) -> str:
    """The inventory body that lives between the markers (markers excluded)."""
    lines: list[str] = [
        "_Generated by `scripts/gen_inventory.py` — do not edit by hand. "
        "Regenerate after adding or removing a module in `src/foliolens/`; "
        "CI fails on drift._",
        "",
        f"{len(rows)} modules. One line per module — first sentence of its "
        "docstring, extracted mechanically.",
    ]
    current: str | None = None
    for package, filename, sentence in rows:
        if package != current:
            lines += ["", f"### `{package}`", ""]
            current = package
        lines.append(f"- `{filename}` — {sentence}")
    return "\n".join(lines)


def splice(existing: str, body: str) -> str:
    """Return ``existing`` with the text between the markers replaced by ``body``."""
    start = existing.find(BEGIN)
    end = existing.find(END)
    if start == -1 or end == -1 or end < start:
        raise SystemExit(
            f"capability-inventory markers not found in {ARCHITECTURE.name}; "
            f"expected both:\n  {BEGIN}\n  {END}"
        )
    head = existing[: start + len(BEGIN)]
    tail = existing[end:]
    return f"{head}\n{body}\n{tail}"


def main() -> None:
    existing = ARCHITECTURE.read_text(encoding="utf-8")
    updated = splice(existing, render_body(collect_modules()))
    ARCHITECTURE.write_text(updated, encoding="utf-8")
    print(f"wrote {ARCHITECTURE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
